begin;

-- Final automatic-ranking archive. The app writes a season here before the
-- commissioner advances the league into the next year.
create table if not exists public.automatic_ranking_history (
  id bigint generated by default as identity primary key,
  season_year integer not null,
  team_id text not null,
  discord_user_id text,
  final_rank integer not null check (final_rank > 0),
  rating numeric(8,2) not null default 0,
  wins integer not null default 0,
  losses integer not null default 0,
  sor numeric(8,2) not null default 0,
  avg_pf numeric(8,2) not null default 0,
  avg_pa numeric(8,2) not null default 0,
  top_10_wins integer not null default 0,
  archived_at timestamptz not null default now(),
  unique(season_year,team_id)
);

create index if not exists automatic_ranking_history_coach_year_idx
  on public.automatic_ranking_history(discord_user_id,season_year);

alter table public.automatic_ranking_history enable row level security;
drop policy if exists ranking_history_read on public.automatic_ranking_history;
create policy ranking_history_read on public.automatic_ranking_history for select to authenticated
  using (public.league_network_current_user_id() is not null);
drop policy if exists ranking_history_commissioner_write on public.automatic_ranking_history;
create policy ranking_history_commissioner_write on public.automatic_ranking_history for all to authenticated
  using (public.league_network_is_commissioner())
  with check (public.league_network_is_commissioner());
revoke all on public.automatic_ranking_history from anon;
grant select,insert,update,delete on public.automatic_ranking_history to authenticated;
grant usage,select on sequence public.automatic_ranking_history_id_seq to authenticated;

-- Anonymous betting consensus without exposing anyone's individual ticket.
create or replace view public.elite_books_pick_consensus as
select
  p.line_id,
  p.pick_slot,
  p.pick_type,
  p.selected_team_id,
  p.selected_total_side,
  count(*)::integer as selection_votes,
  sum(count(*)) over(partition by p.line_id,p.pick_slot)::integer as market_votes,
  round(100.0*count(*)/nullif(sum(count(*)) over(partition by p.line_id,p.pick_slot),0),1) as selection_percentage
from public.sportsbook_picks p
where p.status <> 'void'
group by p.line_id,p.pick_slot,p.pick_type,p.selected_team_id,p.selected_total_side;

create or replace view public.elite_books_future_consensus as
select
  p.market_id,
  p.option_id,
  count(*)::integer as selection_votes,
  sum(count(*)) over(partition by p.market_id)::integer as market_votes,
  round(100.0*count(*)/nullif(sum(count(*)) over(partition by p.market_id),0),1) as selection_percentage,
  dense_rank() over(partition by p.market_id order by count(*) desc,p.option_id)::integer as vote_rank
from public.sportsbook_future_picks p
where p.status <> 'void'
group by p.market_id,p.option_id;

revoke all on public.elite_books_pick_consensus,public.elite_books_future_consensus from anon;
grant select on public.elite_books_pick_consensus,public.elite_books_future_consensus to authenticated;

-- Private, temporary coordination channels for each current user matchup.
alter table public.league_channels
  add column if not exists is_auto_matchup boolean not null default false,
  add column if not exists season_year integer,
  add column if not exists week text,
  add column if not exists matchup_id text;

alter table public.league_channels drop constraint if exists league_channels_channel_type_check;
alter table public.league_channels add constraint league_channels_channel_type_check
  check (channel_type in ('public','announcements','game','sportsbook','streams','matchup'));

create unique index if not exists league_channels_auto_matchup_uidx
  on public.league_channels(matchup_id) where is_auto_matchup;

create or replace function public.league_network_can_view_channel(p_channel_id uuid)
returns boolean language sql stable security definer set search_path=public as $$
  select case
    when public.league_network_is_commissioner() then true
    when public.league_network_current_user_id() is null then false
    else exists(
      select 1
      from public.league_channels c
      left join public.league_channel_permissions cp
        on cp.channel_id=c.id and cp.discord_user_id=public.league_network_current_user_id()
      where c.id=p_channel_id
        and c.is_archived=false
        and case when c.channel_type='matchup' then cp.can_view is true else coalesce(cp.can_view,true) end
    )
  end
$$;

create or replace function public.sync_weekly_matchup_channels(p_season integer,p_week text)
returns integer language plpgsql security definer set search_path=public as $$
declare
  m record;
  v_channel_id uuid;
  v_slug text;
  v_count integer:=0;
begin
  if p_season is null or nullif(trim(p_week),'') is null then return 0; end if;

  update public.league_channels
     set is_archived=true,updated_at=now()
   where is_auto_matchup=true;

  for m in
    select wm.id::text as matchup_id,
           wm.team_1_id::text as team_1_id,
           wm.team_2_id::text as team_2_id,
           coalesce(wm.team_1_user_id::text,(
             select ta.discord_user_id::text from public.team_assignments ta
              where ta.team_id::text=wm.team_1_id::text and (ta.status='Active' or ta.status is null)
              order by ta.created_at desc limit 1
           )) as user_1_id,
           coalesce(wm.team_2_user_id::text,(
             select ta.discord_user_id::text from public.team_assignments ta
              where ta.team_id::text=wm.team_2_id::text and (ta.status='Active' or ta.status is null)
              order by ta.created_at desc limit 1
           )) as user_2_id,
           coalesce(t1.name,'Team 1') as team_1_name,
           coalesce(t2.name,'Team 2') as team_2_name
      from public.weekly_matchups wm
      left join public.teams t1 on t1.id::text=wm.team_1_id::text
      left join public.teams t2 on t2.id::text=wm.team_2_id::text
     where wm.season_year=p_season and wm.week=p_week
  loop
    if m.user_1_id is null or m.user_2_id is null or m.user_1_id=m.user_2_id then continue; end if;
    if not exists(select 1 from public.discord_users du where du.id::text=m.user_1_id and du.is_active is not false and du.is_banned is not true)
       or not exists(select 1 from public.discord_users du where du.id::text=m.user_2_id and du.is_active is not false and du.is_banned is not true) then continue; end if;

    v_slug:='matchup-'||p_season||'-'||regexp_replace(lower(p_week),'[^a-z0-9]+','-','g')||'-'||left(replace(m.matchup_id,'-',''),8);
    insert into public.league_channels(
      slug,name,description,icon,channel_type,sort_order,is_locked,is_archived,
      is_auto_matchup,season_year,week,matchup_id,updated_at
    ) values (
      v_slug,left(m.team_1_name||' vs '||m.team_2_name,60),
      'Private game scheduling for '||m.team_1_name||' and '||m.team_2_name||' • '||p_week,
      'VS','matchup',200+v_count,false,false,true,p_season,p_week,m.matchup_id,now()
    )
    on conflict(matchup_id) where is_auto_matchup do update set
      slug=excluded.slug,name=excluded.name,description=excluded.description,
      is_archived=false,season_year=excluded.season_year,week=excluded.week,updated_at=now()
    returning id into v_channel_id;

    insert into public.league_channel_permissions(channel_id,discord_user_id,can_view,can_post,can_manage,updated_at)
    values(v_channel_id,m.user_1_id,true,true,false,now()),(v_channel_id,m.user_2_id,true,true,false,now())
    on conflict(channel_id,discord_user_id) do update set can_view=true,can_post=true,updated_at=now();
    v_count:=v_count+1;
  end loop;
  return v_count;
end;
$$;

create or replace function public.sync_current_week_matchup_channels_trigger()
returns trigger language plpgsql security definer set search_path=public as $$
declare v_year integer; v_week text;
begin
  select current_year,current_week into v_year,v_week from public.league_settings where id=1;
  perform public.sync_weekly_matchup_channels(v_year,v_week);
  return null;
end;
$$;

drop trigger if exists sync_matchup_channels_on_schedule on public.weekly_matchups;
create trigger sync_matchup_channels_on_schedule
after insert or update or delete on public.weekly_matchups
for each statement execute function public.sync_current_week_matchup_channels_trigger();

drop trigger if exists sync_matchup_channels_on_advance on public.league_settings;
create trigger sync_matchup_channels_on_advance
after insert or update of current_year,current_week on public.league_settings
for each statement execute function public.sync_current_week_matchup_channels_trigger();

grant execute on function public.sync_weekly_matchup_channels(integer,text) to authenticated;

-- Discord-style custom league emoji catalog and private commissioner upload bucket.
create table if not exists public.league_custom_emojis (
  id uuid primary key default gen_random_uuid(),
  name text not null unique check (name ~ '^[a-z0-9_]{2,32}$'),
  image_url text not null,
  storage_path text not null unique,
  created_by text,
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

alter table public.league_custom_emojis enable row level security;
drop policy if exists custom_emoji_read on public.league_custom_emojis;
create policy custom_emoji_read on public.league_custom_emojis for select to authenticated
  using (public.league_network_current_user_id() is not null);
drop policy if exists custom_emoji_commissioner_write on public.league_custom_emojis;
create policy custom_emoji_commissioner_write on public.league_custom_emojis for all to authenticated
  using (public.league_network_is_commissioner())
  with check (public.league_network_is_commissioner());
revoke all on public.league_custom_emojis from anon;
grant select,insert,update,delete on public.league_custom_emojis to authenticated;

insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types)
values('league-emojis','league-emojis',true,524288,array['image/png','image/jpeg','image/webp','image/gif'])
on conflict(id) do update set public=true,file_size_limit=524288,allowed_mime_types=excluded.allowed_mime_types;

drop policy if exists league_emoji_public_read on storage.objects;
create policy league_emoji_public_read on storage.objects for select to authenticated
  using (bucket_id='league-emojis' and public.league_network_current_user_id() is not null);
drop policy if exists league_emoji_commissioner_insert on storage.objects;
create policy league_emoji_commissioner_insert on storage.objects for insert to authenticated
  with check (bucket_id='league-emojis' and public.league_network_is_commissioner());
drop policy if exists league_emoji_commissioner_update on storage.objects;
create policy league_emoji_commissioner_update on storage.objects for update to authenticated
  using (bucket_id='league-emojis' and public.league_network_is_commissioner())
  with check (bucket_id='league-emojis' and public.league_network_is_commissioner());
drop policy if exists league_emoji_commissioner_delete on storage.objects;
create policy league_emoji_commissioner_delete on storage.objects for delete to authenticated
  using (bucket_id='league-emojis' and public.league_network_is_commissioner());

alter table public.league_message_reactions drop constraint if exists league_message_reactions_reaction_check;
alter table public.league_message_reactions add constraint league_message_reactions_reaction_check
  check (char_length(reaction) between 1 and 64);

create or replace function public.toggle_league_message_reaction(p_message_id uuid,p_reaction text)
returns boolean language plpgsql security definer set search_path=public as $$
declare v_user text; v_exists boolean;
begin
  v_user:=public.league_network_current_user_id();
  if v_user is null then raise exception 'Active league membership required'; end if;
  if char_length(p_reaction) not between 1 and 64 then raise exception 'Invalid reaction'; end if;
  if not exists(select 1 from public.league_channel_messages m where m.id=p_message_id and m.deleted_at is null and public.league_network_can_view_channel(m.channel_id)) then raise exception 'Message not found'; end if;
  select exists(select 1 from public.league_message_reactions where message_id=p_message_id and discord_user_id=v_user and reaction=p_reaction) into v_exists;
  if v_exists then
    delete from public.league_message_reactions where message_id=p_message_id and discord_user_id=v_user and reaction=p_reaction;
    return false;
  end if;
  insert into public.league_message_reactions(message_id,discord_user_id,reaction) values(p_message_id,v_user,p_reaction) on conflict do nothing;
  return true;
end;
$$;

grant execute on function public.toggle_league_message_reaction(uuid,text) to authenticated;

-- Create the current week's private matchup rooms immediately.
do $$
declare v_year integer; v_week text;
begin
  select current_year,current_week into v_year,v_week from public.league_settings where id=1;
  perform public.sync_weekly_matchup_channels(v_year,v_week);
end $$;

commit;

select 'CFBElite 27 v28 league experience migration complete' as status;
